# Writes a C++ source of {relative path, contents} entries in list order, run with cmake -P
# Contents are one literal, or with CHUNK_BYTES an array of literals of at most that size
foreach(input BASE_DIR FILE_LIST OUTPUT HEADER NAMESPACE TYPE FUNCTION)
    if(NOT DEFINED ${input})
        message(FATAL_ERROR "EmbedFiles.cmake needs -D${input}=...")
    endif()
endforeach()

# Every byte becomes a \xNN escape, in adjacent literals of at most 4000 bytes
# so no piece nears MSVC's 16380 character limit per literal
function(hex_to_literal hex out_var)
    string(LENGTH "${hex}" length)
    if(length EQUAL 0)
        set(${out_var} "\"\"sv" PARENT_SCOPE)
        return()
    endif()
    set(literal "")
    math(EXPR last "${length} - 1")
    foreach(start RANGE 0 ${last} 8000)
        string(SUBSTRING "${hex}" ${start} 8000 piece)
        string(REGEX REPLACE "(..)" "\\\\x\\1" piece "${piece}")
        string(APPEND literal "\n        \"${piece}\"")
    endforeach()
    set(${out_var} "${literal}sv" PARENT_SCOPE)
endfunction()

# The declaration of kChunks<index>, one literal per CHUNK_BYTES of the hex contents
function(hex_to_chunks hex index out_var)
    string(LENGTH "${hex}" length)
    math(EXPR step "${CHUNK_BYTES} * 2")
    set(chunks "")
    set(chunk_count 0)
    if(length GREATER 0)
        math(EXPR last "${length} - 1")
        foreach(start RANGE 0 ${last} ${step})
            string(SUBSTRING "${hex}" ${start} ${step} chunk)
            hex_to_literal("${chunk}" literal)
            string(APPEND chunks "${literal},")
            math(EXPR chunk_count "${chunk_count} + 1")
        endforeach()
    endif()
    set(${out_var}
        "constexpr std::array<std::string_view, ${chunk_count}> kChunks${index} = {{${chunks}\n}};\n\n"
        PARENT_SCOPE)
endfunction()

# FILE_LIST holds a CMake list of paths relative to BASE_DIR, already sorted
file(READ "${FILE_LIST}" files)
list(LENGTH files count)

set(chunk_decls "")
set(entries "")
set(index 0)
foreach(path IN LISTS files)
    string(HEX "${path}" path_hex)
    file(READ "${BASE_DIR}/${path}" text_hex HEX)
    hex_to_literal("${path_hex}" path_literal)
    if(DEFINED CHUNK_BYTES)
        hex_to_chunks("${text_hex}" ${index} chunk_decl)
        string(APPEND chunk_decls "${chunk_decl}")
        string(APPEND entries "    {${path_literal}, kChunks${index}},\n")
    else()
        hex_to_literal("${text_hex}" text_literal)
        string(APPEND entries "    {${path_literal},${text_literal}},\n")
    endif()
    math(EXPR index "${index} + 1")
endforeach()

set(source "// Generated by EmbedFiles.cmake, do not edit
#include \"${HEADER}\"

#include <array>
#include <string_view>

namespace ${NAMESPACE} {

namespace {

using std::string_view_literals::operator\"\"sv;

${chunk_decls}constexpr std::array<${TYPE}, ${count}> kFiles = {{
${entries}}};

}  // namespace

std::span<const ${TYPE}> ${FUNCTION}() noexcept {
    return kFiles;
}

}  // namespace ${NAMESPACE}
")

# Replace the output only when it changed, so unchanged inputs never recompile it
file(WRITE "${OUTPUT}.tmp" "${source}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
