# Writes a C++ source holding a table of {relative path, contents} entries, one
# per listed file in list order. Run it in script mode with cmake -P
foreach(input BASE_DIR FILE_LIST OUTPUT HEADER NAMESPACE TYPE FUNCTION)
    if(NOT DEFINED ${input})
        message(FATAL_ERROR "EmbedFiles.cmake needs -D${input}=...")
    endif()
endforeach()

# Every byte becomes a \xNN escape, in adjacent literals of at most 4000 bytes
# so no piece nears MSVC's 16380 character limit per literal
function(hex_to_literal hex out_var)
    string(LENGTH "${hex}" length)
    if(length EQUAL 0)
        set(${out_var} "\"\"sv" PARENT_SCOPE)
        return()
    endif()
    set(literal "")
    math(EXPR last "${length} - 1")
    foreach(start RANGE 0 ${last} 8000)
        string(SUBSTRING "${hex}" ${start} 8000 piece)
        string(REGEX REPLACE "(..)" "\\\\x\\1" piece "${piece}")
        string(APPEND literal "\n        \"${piece}\"")
    endforeach()
    set(${out_var} "${literal}sv" PARENT_SCOPE)
endfunction()

# FILE_LIST holds a CMake list of paths relative to BASE_DIR, already sorted
file(READ "${FILE_LIST}" files)
list(LENGTH files count)

set(entries "")
foreach(path IN LISTS files)
    string(HEX "${path}" path_hex)
    file(READ "${BASE_DIR}/${path}" text_hex HEX)
    hex_to_literal("${path_hex}" path_literal)
    hex_to_literal("${text_hex}" text_literal)
    string(APPEND entries "    {${path_literal},${text_literal}},\n")
endforeach()

set(source "// Generated by EmbedFiles.cmake, do not edit
#include \"${HEADER}\"

#include <array>
#include <string_view>

namespace ${NAMESPACE} {

namespace {

using std::string_view_literals::operator\"\"sv;

constexpr std::array<${TYPE}, ${count}> kFiles = {{
${entries}}};

}  // namespace

std::span<const ${TYPE}> ${FUNCTION}() noexcept {
    return kFiles;
}

}  // namespace ${NAMESPACE}
")

# Replace the output only when it changed, so unchanged inputs never recompile it
file(WRITE "${OUTPUT}.tmp" "${source}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
